import pandas as pd
import matplotlib.pyplot as plt
Excel=pd.read_csv("athlete_events-1.csv")
print("Datos iniciales:")
print(Excel.head())
print("")
print("")
ConMedallas=Excel.copy()
ConMedallas=ConMedallas.dropna(subset="Medal")
Frecuencia=ConMedallas["NOC"].value_counts()
Frecuencia=Frecuencia.head(10)
Frecuencia=Frecuencia.to_frame()
Frecuencia=Frecuencia.reset_index()
Medallas=Frecuencia["NOC"].to_list()
Paises=Frecuencia["index"].to_list()
PaisesYMedallas=pd.DataFrame({"Medallas":Medallas},index=Paises)
print("Lsita de paises con mayor numero de medallas:")
print(PaisesYMedallas)
plt.bar(Paises,Medallas)
plt.xlabel("Paises")
plt.ylabel("Medallas")
plt.title("Paises con mayor numero de medallas")
plt.show()

